<a href="<?=$usersLink?>">All users</a>
<form action="/users" method="post">
  <input type="hidden" name="user[title]" value="new">
  <input type="hidden" name="user[paid]" value="paid">
  <div>
    <label>
        Имя<br>
      <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name'] ?? '') ?>">
    </label>
    <?php if (isset($errors['name'])): ?>
      <div><?= $errors['name'] ?></div>
    <?php endif ?>
  </div>
  <div>
    <label>
        Email<br>
      <input type="email" name="user[email]" value="<?= htmlspecialchars($user['email'] ?? '') ?>">
    </label>
    <?php if (isset($errors['email'])): ?>
      <div><?= $errors['email'] ?></div>
    <?php endif ?>
  </div>
  <div>
    <label>
        Пароль<br>
      <input type="password" required name="user[password]" value="<?= htmlspecialchars($user['password'] ?? '') ?>">
    </label>
    <?php if (isset($errors['password'])): ?>
      <div><?= $errors['password'] ?></div>
    <?php endif ?>
  </div>
  <div>
    <label>
        Подтверждение пароля<br>
      <input type="password" required name="user[passwordConfirmation]" value="<?= htmlspecialchars($user['passwordConfirmation'] ?? '') ?>">
    </label>
  </div>
  <div>
    <label>
      <br>
      Город<br>
      <select name="user[city]">
        <option value="">Select</option>
        <option <?= isset($user['city']) && $user['city'] === '3' ? 'selected' : '' ?> value="3">Москва</option>
        <option <?= isset($user['city']) && $user['city'] === '13' ? 'selected' : '' ?> value="13">Пенза</option>
        <option <?= isset($user['city']) && $user['city'] === '399' ? 'selected' : '' ?> value="399">Томск</option>
      </select>
    </label>
    <?php if (isset($errors['city'])): ?>
      <div><?= $errors['city'] ?></div>
    <?php endif ?>
  </div>
  <br>
  <input type="submit" value="Sign Up">
</form>